openapi: 3.0.3
info:
  title: Go Analyzer Service
  version: 1.1.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /analyze:
    get:
      summary: Analyze sentence (query)
      security:
        - BearerAuth: []    # <— requires JWT
      parameters:
        - in: query
          name: sentence
          required: true
          schema: { type: string }
      responses:
        '200': { description: Analysis result }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
    post:
      summary: Analyze sentence (JSON body)
      security:
        - BearerAuth: []    # <— requires JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequest'
      responses:
        '200': { description: Analysis result }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
components:
  schemas:
    AnalyzeRequest:
      type: object
      required: [sentence]
      properties:
        sentence: { type: string, example: Hello, world! }
