apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-analyzer
  labels:
    app: go-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-analyzer
  template:
    metadata:
      labels:
        app: go-analyzer
    spec:
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
